name: Test Docker Build

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

env:
  AWS_DEFAULT_REGION: us-west-2

jobs:
  run-docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.3]

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Ref: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::445123149871:role/optica-github-actions
          role-session-name: ibkr-client-portal-api-github-pr-test
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Ref: https://github.com/aws-actions/amazon-ecr-login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test docker build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          platforms: linux/amd64
          tags: ibkr-client-portal-api-build-test:latest-${{ github.sha }}
