version: "2.1"

services:
  ibkr-client-portal-api:
    image: ibkr-client-portal-api:latest
    platform: linux/amd64
    # platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "ibkr-client-portal-api:latest"
    container_name: ibeam
    env_file:
      - .env.master.paper
    ports:
      - 127.0.0.1:5000:5000
      - 127.0.0.1:5001:5001
    network_mode: bridge # Required due to clientportal.gw IP restrictions
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
